config/routes.rb
Rails.application.routes.draw do
  root 'records#index'
  resources:records
  get 'about' => 'static_pages#about'
end

app/models/record.rb
class Record < ActiveRecord::Base
    validates :title, :date, :amount, presence: true
    def self.balance
        where("amount>?",0).sum(:amount)
    end

    def self.debt
        where("amount<?",0).sum(:amount)
    end

    def self.total
        total= (self.balance + self.debt) 
        return total
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
    def index
 	@records= Record.all
 	@balance=Record.balance
	@debt=Record.debt
 	@total=Record.total
 	end
 	
 	def create
	@records= Record.create(record_params)
	if @records.valid?
		flash[:success] = "Your record has been posted!"
		redirect_to root_path
 	else
		flash[:alert] = "Woops! Looks like there has been an error!"
	end
 	end
 	
 	def new
 		@record=Record.new
 	end
 	def edit
		 @records = Record.find(params[:id])
	end
	def update
		@records = Record.find(params[:id])
			if @records.update(record_params)
				flash[:success] = "The record has been updated!"
				redirect_to root_path
			else
				flash[:alert] = "Woops! Looks like there has been an error!"
				redirect_to edit_account_path(params[:id])
    		end
	end
	def destroy
		@records=Record.find(params[:id])
		@records.destroy
		flash[:success] = "The record was successfully deleted!"
		redirect_to root_path
	end
	
	private
	def record_params
		params.require(:record).permit(:title, :date , :amount)
	end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
    def about
        
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
 <link href="https://fonts.googleapis.com/css?family=Asap:600,600i|Bree+Serif&amp;subset=latin-ext" rel="stylesheet">
  <title>Track your Finance</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <%= render 'shared/nav' %>
</nav>
<%= yield %>
</body>
</html>

app/views/records/edit.html.erb
<h1> Update your record</h1>
<%= simple_form_for @records, method: :patch do |f| %>
<%= f.input :title %>
<%= f.input :date %>
<%= f.input :amount %>
<%= f.submit 'Submit', class: 'btn btn-primary' %>
<% end %>

app/views/records/index.html.erb
<div class="panel panel-primary">
<div class="panel-body",background:#F9EECF>

    <h3>Balance= <%= @balance %></h3>
    <h3>Debt= <%= @debt %></h3>
    <h3>Total= <%= @total %></h3>
</div>
</div>

<div class="col-md-12">
        <h1>Records</h1>
        <hr>
        <table class="table">
            <tr>
                <th>Title</th>
                <th>Date</th>
                <th>Amount</th>
                <th>Action</th>
            </tr>
            <% @records.each do|record| %>
            <tr>
                <td><%= record.title %></td>
                <td><%= record.date %></td>
                <td><%= record.amount %></td> 
                <td>
                    <%= link_to 'Delete', record_path(record), method: :delete, class: 'btn btn-sm btn-danger', data: {confirm: "Are you sure?"} %>
                      <%= link_to 'Update', edit_record_path(record), class: 'btn btn-sm btn-success' %>
                </td>
            </tr>
            <% end %>
         </table>
</div>

app/views/records/new.html.erb
<%= simple_form_for Record.new do |record| %>
    <%= record.input :title %>
    <%= record.input :date %>
    <%= record.input :amount %>
     <%= record.submit 'Add Record', class: 'btn btn-primary' %>
    <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
<% end %>   

app/views/shared/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <% if message_type == "notice" %>
    <p class="alert alert-info alert-dismissible text-center"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button><%= notice %></p>
  <% elsif message_type == "alert" %>
    <p class="alert alert-danger alert-dismissible text-center"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button><%= alert %></p>
  <% else %>
    <div class="alert alert-<%= message_type %> alert-dismissible text-center"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button><%= message %></div>
  <% end %>
<% end %>

app/views/shared/_nav.html.erb
<div class="navbar-header">
    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="/">Track Your Finance</a>
    
  </div>
    
    <ul class="nav navbar-nav navbar-right">
      <li><%= link_to 'Add record', new_record_path %></li>
      <li><%= link_to 'About', about_path %></li>
    </ul>
</div>